/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_morkva_engine_Controller */

#ifndef _Included_com_morkva_engine_Controller
#define _Included_com_morkva_engine_Controller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_morkva_engine_Controller
 * Method:    getContent
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_morkva_engine_Controller_getContent
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
